// Generated by tools/gen_wire.py. Do not edit by hand.
//
// Source: Nasdaq TotalView-ITCH 5.0 specification
//   https://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHspecification.pdf
//   sha256 45e0531d1b4b3beb886e9618b2ab824a5aa9bda3a99c0dff03509306e68aacc3
//
// These structs pin down the wire layout and let the compiler check every
// offset. They are NOT the parse path: casting a const std::byte* to one of
// them is undefined on both alignment and aliasing grounds. Fields are read
// with load_be<T>(p + offsetof(Struct, field)) instead, so the layout here
// stays the single source of truth for every offset without any cast.
//
// Every member is a byte array, so alignment is 1 by construction and there
// is no padding anywhere. Both facts are asserted below rather than assumed.
#pragma once

#include <cstddef>
#include <type_traits>

#include "itch/core/types.hpp"

namespace itch::wire {

template <std::size_t N>
struct Bytes {
    std::byte raw[N];
};

template <std::size_t N>
struct Alpha {
    char raw[N];
};

using BeU16 = Bytes<2>;
using BeU32 = Bytes<4>;
using BeU48 = Bytes<6>;  // ITCH timestamps: nanoseconds since midnight
using BeU64 = Bytes<8>;
using Price4 = Bytes<4>;  // unsigned, four implied decimals
using Price8 = Bytes<8>;  // unsigned, four implied decimals

// Longest message in the protocol. Sizing a framing buffer below this means
// a message can straddle the end of it.
inline constexpr std::size_t kMaxMessageLength = 50;
inline constexpr std::size_t kMessageTypeCount = 23;

enum class MsgType : char {
    SystemEvent = 'S',
    StockDirectory = 'R',
    StockTradingAction = 'H',
    RegShoRestriction = 'Y',
    MarketParticipantPosition = 'L',
    MwcbDeclineLevel = 'V',
    MwcbStatus = 'W',
    IpoQuotingPeriodUpdate = 'K',
    LuldAuctionCollar = 'J',
    OperationalHalt = 'h',
    AddOrder = 'A',
    AddOrderWithMpid = 'F',
    OrderExecuted = 'E',
    OrderExecutedWithPrice = 'C',
    OrderCancel = 'X',
    OrderDelete = 'D',
    OrderReplace = 'U',
    TradeNonCross = 'P',
    CrossTrade = 'Q',
    BrokenTrade = 'B',
    Noii = 'I',
    RetailPriceImprovement = 'N',
    DirectListingWithCapitalRaise = 'O',
};

// 'S' -- System Event Message (12 bytes)
struct SystemEvent {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<1>   event_code;
};
static_assert(sizeof(SystemEvent) == 12, "SystemEvent wire size");
static_assert(alignof(SystemEvent) == 1, "SystemEvent must have no alignment padding");
static_assert(std::is_standard_layout_v<SystemEvent>, "SystemEvent must be standard layout for offsetof");
static_assert(offsetof(SystemEvent, message_type) == 0, "SystemEvent::message_type offset");
static_assert(sizeof(SystemEvent::message_type) == 1, "SystemEvent::message_type length");
static_assert(offsetof(SystemEvent, stock_locate) == 1, "SystemEvent::stock_locate offset");
static_assert(sizeof(SystemEvent::stock_locate) == 2, "SystemEvent::stock_locate length");
static_assert(offsetof(SystemEvent, tracking_number) == 3, "SystemEvent::tracking_number offset");
static_assert(sizeof(SystemEvent::tracking_number) == 2, "SystemEvent::tracking_number length");
static_assert(offsetof(SystemEvent, timestamp) == 5, "SystemEvent::timestamp offset");
static_assert(sizeof(SystemEvent::timestamp) == 6, "SystemEvent::timestamp length");
static_assert(offsetof(SystemEvent, event_code) == 11, "SystemEvent::event_code offset");
static_assert(sizeof(SystemEvent::event_code) == 1, "SystemEvent::event_code length");

// 'R' -- Stock Directory Message (39 bytes)
struct StockDirectory {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Alpha<1>   market_category;
    Alpha<1>   financial_status_indicator;
    BeU32      round_lot_size;
    Alpha<1>   round_lots_only;
    Alpha<1>   issue_classification;
    Alpha<2>   issue_sub_type;
    Alpha<1>   authenticity;
    Alpha<1>   short_sale_threshold_indicator;
    Alpha<1>   ipo_flag;
    Alpha<1>   luld_reference_price_tier;
    Alpha<1>   etp_flag;
    BeU32      etp_leverage_factor;
    Alpha<1>   inverse_indicator;
};
static_assert(sizeof(StockDirectory) == 39, "StockDirectory wire size");
static_assert(alignof(StockDirectory) == 1, "StockDirectory must have no alignment padding");
static_assert(std::is_standard_layout_v<StockDirectory>, "StockDirectory must be standard layout for offsetof");
static_assert(offsetof(StockDirectory, message_type) == 0, "StockDirectory::message_type offset");
static_assert(sizeof(StockDirectory::message_type) == 1, "StockDirectory::message_type length");
static_assert(offsetof(StockDirectory, stock_locate) == 1, "StockDirectory::stock_locate offset");
static_assert(sizeof(StockDirectory::stock_locate) == 2, "StockDirectory::stock_locate length");
static_assert(offsetof(StockDirectory, tracking_number) == 3, "StockDirectory::tracking_number offset");
static_assert(sizeof(StockDirectory::tracking_number) == 2, "StockDirectory::tracking_number length");
static_assert(offsetof(StockDirectory, timestamp) == 5, "StockDirectory::timestamp offset");
static_assert(sizeof(StockDirectory::timestamp) == 6, "StockDirectory::timestamp length");
static_assert(offsetof(StockDirectory, stock) == 11, "StockDirectory::stock offset");
static_assert(sizeof(StockDirectory::stock) == 8, "StockDirectory::stock length");
static_assert(offsetof(StockDirectory, market_category) == 19, "StockDirectory::market_category offset");
static_assert(sizeof(StockDirectory::market_category) == 1, "StockDirectory::market_category length");
static_assert(offsetof(StockDirectory, financial_status_indicator) == 20, "StockDirectory::financial_status_indicator offset");
static_assert(sizeof(StockDirectory::financial_status_indicator) == 1, "StockDirectory::financial_status_indicator length");
static_assert(offsetof(StockDirectory, round_lot_size) == 21, "StockDirectory::round_lot_size offset");
static_assert(sizeof(StockDirectory::round_lot_size) == 4, "StockDirectory::round_lot_size length");
static_assert(offsetof(StockDirectory, round_lots_only) == 25, "StockDirectory::round_lots_only offset");
static_assert(sizeof(StockDirectory::round_lots_only) == 1, "StockDirectory::round_lots_only length");
static_assert(offsetof(StockDirectory, issue_classification) == 26, "StockDirectory::issue_classification offset");
static_assert(sizeof(StockDirectory::issue_classification) == 1, "StockDirectory::issue_classification length");
static_assert(offsetof(StockDirectory, issue_sub_type) == 27, "StockDirectory::issue_sub_type offset");
static_assert(sizeof(StockDirectory::issue_sub_type) == 2, "StockDirectory::issue_sub_type length");
static_assert(offsetof(StockDirectory, authenticity) == 29, "StockDirectory::authenticity offset");
static_assert(sizeof(StockDirectory::authenticity) == 1, "StockDirectory::authenticity length");
static_assert(offsetof(StockDirectory, short_sale_threshold_indicator) == 30, "StockDirectory::short_sale_threshold_indicator offset");
static_assert(sizeof(StockDirectory::short_sale_threshold_indicator) == 1, "StockDirectory::short_sale_threshold_indicator length");
static_assert(offsetof(StockDirectory, ipo_flag) == 31, "StockDirectory::ipo_flag offset");
static_assert(sizeof(StockDirectory::ipo_flag) == 1, "StockDirectory::ipo_flag length");
static_assert(offsetof(StockDirectory, luld_reference_price_tier) == 32, "StockDirectory::luld_reference_price_tier offset");
static_assert(sizeof(StockDirectory::luld_reference_price_tier) == 1, "StockDirectory::luld_reference_price_tier length");
static_assert(offsetof(StockDirectory, etp_flag) == 33, "StockDirectory::etp_flag offset");
static_assert(sizeof(StockDirectory::etp_flag) == 1, "StockDirectory::etp_flag length");
static_assert(offsetof(StockDirectory, etp_leverage_factor) == 34, "StockDirectory::etp_leverage_factor offset");
static_assert(sizeof(StockDirectory::etp_leverage_factor) == 4, "StockDirectory::etp_leverage_factor length");
static_assert(offsetof(StockDirectory, inverse_indicator) == 38, "StockDirectory::inverse_indicator offset");
static_assert(sizeof(StockDirectory::inverse_indicator) == 1, "StockDirectory::inverse_indicator length");

// 'H' -- Stock Trading Action Message (25 bytes)
struct StockTradingAction {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Alpha<1>   trading_state;
    Alpha<1>   reserved;
    Alpha<4>   reason;
};
static_assert(sizeof(StockTradingAction) == 25, "StockTradingAction wire size");
static_assert(alignof(StockTradingAction) == 1, "StockTradingAction must have no alignment padding");
static_assert(std::is_standard_layout_v<StockTradingAction>, "StockTradingAction must be standard layout for offsetof");
static_assert(offsetof(StockTradingAction, message_type) == 0, "StockTradingAction::message_type offset");
static_assert(sizeof(StockTradingAction::message_type) == 1, "StockTradingAction::message_type length");
static_assert(offsetof(StockTradingAction, stock_locate) == 1, "StockTradingAction::stock_locate offset");
static_assert(sizeof(StockTradingAction::stock_locate) == 2, "StockTradingAction::stock_locate length");
static_assert(offsetof(StockTradingAction, tracking_number) == 3, "StockTradingAction::tracking_number offset");
static_assert(sizeof(StockTradingAction::tracking_number) == 2, "StockTradingAction::tracking_number length");
static_assert(offsetof(StockTradingAction, timestamp) == 5, "StockTradingAction::timestamp offset");
static_assert(sizeof(StockTradingAction::timestamp) == 6, "StockTradingAction::timestamp length");
static_assert(offsetof(StockTradingAction, stock) == 11, "StockTradingAction::stock offset");
static_assert(sizeof(StockTradingAction::stock) == 8, "StockTradingAction::stock length");
static_assert(offsetof(StockTradingAction, trading_state) == 19, "StockTradingAction::trading_state offset");
static_assert(sizeof(StockTradingAction::trading_state) == 1, "StockTradingAction::trading_state length");
static_assert(offsetof(StockTradingAction, reserved) == 20, "StockTradingAction::reserved offset");
static_assert(sizeof(StockTradingAction::reserved) == 1, "StockTradingAction::reserved length");
static_assert(offsetof(StockTradingAction, reason) == 21, "StockTradingAction::reason offset");
static_assert(sizeof(StockTradingAction::reason) == 4, "StockTradingAction::reason length");

// 'Y' -- Reg SHO Short Sale Price Test Restricted Indicator (20 bytes)
struct RegShoRestriction {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Alpha<1>   reg_sho_action;
};
static_assert(sizeof(RegShoRestriction) == 20, "RegShoRestriction wire size");
static_assert(alignof(RegShoRestriction) == 1, "RegShoRestriction must have no alignment padding");
static_assert(std::is_standard_layout_v<RegShoRestriction>, "RegShoRestriction must be standard layout for offsetof");
static_assert(offsetof(RegShoRestriction, message_type) == 0, "RegShoRestriction::message_type offset");
static_assert(sizeof(RegShoRestriction::message_type) == 1, "RegShoRestriction::message_type length");
static_assert(offsetof(RegShoRestriction, stock_locate) == 1, "RegShoRestriction::stock_locate offset");
static_assert(sizeof(RegShoRestriction::stock_locate) == 2, "RegShoRestriction::stock_locate length");
static_assert(offsetof(RegShoRestriction, tracking_number) == 3, "RegShoRestriction::tracking_number offset");
static_assert(sizeof(RegShoRestriction::tracking_number) == 2, "RegShoRestriction::tracking_number length");
static_assert(offsetof(RegShoRestriction, timestamp) == 5, "RegShoRestriction::timestamp offset");
static_assert(sizeof(RegShoRestriction::timestamp) == 6, "RegShoRestriction::timestamp length");
static_assert(offsetof(RegShoRestriction, stock) == 11, "RegShoRestriction::stock offset");
static_assert(sizeof(RegShoRestriction::stock) == 8, "RegShoRestriction::stock length");
static_assert(offsetof(RegShoRestriction, reg_sho_action) == 19, "RegShoRestriction::reg_sho_action offset");
static_assert(sizeof(RegShoRestriction::reg_sho_action) == 1, "RegShoRestriction::reg_sho_action length");

// 'L' -- Market Participant Position message (26 bytes)
struct MarketParticipantPosition {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<4>   mpid;
    Alpha<8>   stock;
    Alpha<1>   primary_market;
    Alpha<1>   market_maker_mode;
    Alpha<1>   market_participant_state;
};
static_assert(sizeof(MarketParticipantPosition) == 26, "MarketParticipantPosition wire size");
static_assert(alignof(MarketParticipantPosition) == 1, "MarketParticipantPosition must have no alignment padding");
static_assert(std::is_standard_layout_v<MarketParticipantPosition>, "MarketParticipantPosition must be standard layout for offsetof");
static_assert(offsetof(MarketParticipantPosition, message_type) == 0, "MarketParticipantPosition::message_type offset");
static_assert(sizeof(MarketParticipantPosition::message_type) == 1, "MarketParticipantPosition::message_type length");
static_assert(offsetof(MarketParticipantPosition, stock_locate) == 1, "MarketParticipantPosition::stock_locate offset");
static_assert(sizeof(MarketParticipantPosition::stock_locate) == 2, "MarketParticipantPosition::stock_locate length");
static_assert(offsetof(MarketParticipantPosition, tracking_number) == 3, "MarketParticipantPosition::tracking_number offset");
static_assert(sizeof(MarketParticipantPosition::tracking_number) == 2, "MarketParticipantPosition::tracking_number length");
static_assert(offsetof(MarketParticipantPosition, timestamp) == 5, "MarketParticipantPosition::timestamp offset");
static_assert(sizeof(MarketParticipantPosition::timestamp) == 6, "MarketParticipantPosition::timestamp length");
static_assert(offsetof(MarketParticipantPosition, mpid) == 11, "MarketParticipantPosition::mpid offset");
static_assert(sizeof(MarketParticipantPosition::mpid) == 4, "MarketParticipantPosition::mpid length");
static_assert(offsetof(MarketParticipantPosition, stock) == 15, "MarketParticipantPosition::stock offset");
static_assert(sizeof(MarketParticipantPosition::stock) == 8, "MarketParticipantPosition::stock length");
static_assert(offsetof(MarketParticipantPosition, primary_market) == 23, "MarketParticipantPosition::primary_market offset");
static_assert(sizeof(MarketParticipantPosition::primary_market) == 1, "MarketParticipantPosition::primary_market length");
static_assert(offsetof(MarketParticipantPosition, market_maker_mode) == 24, "MarketParticipantPosition::market_maker_mode offset");
static_assert(sizeof(MarketParticipantPosition::market_maker_mode) == 1, "MarketParticipantPosition::market_maker_mode length");
static_assert(offsetof(MarketParticipantPosition, market_participant_state) == 25, "MarketParticipantPosition::market_participant_state offset");
static_assert(sizeof(MarketParticipantPosition::market_participant_state) == 1, "MarketParticipantPosition::market_participant_state length");

// 'V' -- Market wide circuit breaker Decline Level Message (35 bytes)
struct MwcbDeclineLevel {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Price8     level_1;
    Price8     level_2;
    Price8     level_3;
};
static_assert(sizeof(MwcbDeclineLevel) == 35, "MwcbDeclineLevel wire size");
static_assert(alignof(MwcbDeclineLevel) == 1, "MwcbDeclineLevel must have no alignment padding");
static_assert(std::is_standard_layout_v<MwcbDeclineLevel>, "MwcbDeclineLevel must be standard layout for offsetof");
static_assert(offsetof(MwcbDeclineLevel, message_type) == 0, "MwcbDeclineLevel::message_type offset");
static_assert(sizeof(MwcbDeclineLevel::message_type) == 1, "MwcbDeclineLevel::message_type length");
static_assert(offsetof(MwcbDeclineLevel, stock_locate) == 1, "MwcbDeclineLevel::stock_locate offset");
static_assert(sizeof(MwcbDeclineLevel::stock_locate) == 2, "MwcbDeclineLevel::stock_locate length");
static_assert(offsetof(MwcbDeclineLevel, tracking_number) == 3, "MwcbDeclineLevel::tracking_number offset");
static_assert(sizeof(MwcbDeclineLevel::tracking_number) == 2, "MwcbDeclineLevel::tracking_number length");
static_assert(offsetof(MwcbDeclineLevel, timestamp) == 5, "MwcbDeclineLevel::timestamp offset");
static_assert(sizeof(MwcbDeclineLevel::timestamp) == 6, "MwcbDeclineLevel::timestamp length");
static_assert(offsetof(MwcbDeclineLevel, level_1) == 11, "MwcbDeclineLevel::level_1 offset");
static_assert(sizeof(MwcbDeclineLevel::level_1) == 8, "MwcbDeclineLevel::level_1 length");
static_assert(offsetof(MwcbDeclineLevel, level_2) == 19, "MwcbDeclineLevel::level_2 offset");
static_assert(sizeof(MwcbDeclineLevel::level_2) == 8, "MwcbDeclineLevel::level_2 length");
static_assert(offsetof(MwcbDeclineLevel, level_3) == 27, "MwcbDeclineLevel::level_3 offset");
static_assert(sizeof(MwcbDeclineLevel::level_3) == 8, "MwcbDeclineLevel::level_3 length");

// 'W' -- Market-Wide Circuit Breaker Status message (12 bytes)
struct MwcbStatus {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<1>   breached_level;
};
static_assert(sizeof(MwcbStatus) == 12, "MwcbStatus wire size");
static_assert(alignof(MwcbStatus) == 1, "MwcbStatus must have no alignment padding");
static_assert(std::is_standard_layout_v<MwcbStatus>, "MwcbStatus must be standard layout for offsetof");
static_assert(offsetof(MwcbStatus, message_type) == 0, "MwcbStatus::message_type offset");
static_assert(sizeof(MwcbStatus::message_type) == 1, "MwcbStatus::message_type length");
static_assert(offsetof(MwcbStatus, stock_locate) == 1, "MwcbStatus::stock_locate offset");
static_assert(sizeof(MwcbStatus::stock_locate) == 2, "MwcbStatus::stock_locate length");
static_assert(offsetof(MwcbStatus, tracking_number) == 3, "MwcbStatus::tracking_number offset");
static_assert(sizeof(MwcbStatus::tracking_number) == 2, "MwcbStatus::tracking_number length");
static_assert(offsetof(MwcbStatus, timestamp) == 5, "MwcbStatus::timestamp offset");
static_assert(sizeof(MwcbStatus::timestamp) == 6, "MwcbStatus::timestamp length");
static_assert(offsetof(MwcbStatus, breached_level) == 11, "MwcbStatus::breached_level offset");
static_assert(sizeof(MwcbStatus::breached_level) == 1, "MwcbStatus::breached_level length");

// 'K' -- IPO Quoting Period Update Message (28 bytes)
struct IpoQuotingPeriodUpdate {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    BeU32      ipo_quotation_release_time;
    Alpha<1>   ipo_quotation_release_qualifier;
    Price4     ipo_price;
};
static_assert(sizeof(IpoQuotingPeriodUpdate) == 28, "IpoQuotingPeriodUpdate wire size");
static_assert(alignof(IpoQuotingPeriodUpdate) == 1, "IpoQuotingPeriodUpdate must have no alignment padding");
static_assert(std::is_standard_layout_v<IpoQuotingPeriodUpdate>, "IpoQuotingPeriodUpdate must be standard layout for offsetof");
static_assert(offsetof(IpoQuotingPeriodUpdate, message_type) == 0, "IpoQuotingPeriodUpdate::message_type offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::message_type) == 1, "IpoQuotingPeriodUpdate::message_type length");
static_assert(offsetof(IpoQuotingPeriodUpdate, stock_locate) == 1, "IpoQuotingPeriodUpdate::stock_locate offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::stock_locate) == 2, "IpoQuotingPeriodUpdate::stock_locate length");
static_assert(offsetof(IpoQuotingPeriodUpdate, tracking_number) == 3, "IpoQuotingPeriodUpdate::tracking_number offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::tracking_number) == 2, "IpoQuotingPeriodUpdate::tracking_number length");
static_assert(offsetof(IpoQuotingPeriodUpdate, timestamp) == 5, "IpoQuotingPeriodUpdate::timestamp offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::timestamp) == 6, "IpoQuotingPeriodUpdate::timestamp length");
static_assert(offsetof(IpoQuotingPeriodUpdate, stock) == 11, "IpoQuotingPeriodUpdate::stock offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::stock) == 8, "IpoQuotingPeriodUpdate::stock length");
static_assert(offsetof(IpoQuotingPeriodUpdate, ipo_quotation_release_time) == 19, "IpoQuotingPeriodUpdate::ipo_quotation_release_time offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::ipo_quotation_release_time) == 4, "IpoQuotingPeriodUpdate::ipo_quotation_release_time length");
static_assert(offsetof(IpoQuotingPeriodUpdate, ipo_quotation_release_qualifier) == 23, "IpoQuotingPeriodUpdate::ipo_quotation_release_qualifier offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::ipo_quotation_release_qualifier) == 1, "IpoQuotingPeriodUpdate::ipo_quotation_release_qualifier length");
static_assert(offsetof(IpoQuotingPeriodUpdate, ipo_price) == 24, "IpoQuotingPeriodUpdate::ipo_price offset");
static_assert(sizeof(IpoQuotingPeriodUpdate::ipo_price) == 4, "IpoQuotingPeriodUpdate::ipo_price length");

// 'J' -- LULD Auction Collar (35 bytes)
struct LuldAuctionCollar {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Price4     auction_collar_reference_price;
    Price4     upper_auction_collar_price;
    Price4     lower_auction_collar_price;
    BeU32      auction_collar_extension;
};
static_assert(sizeof(LuldAuctionCollar) == 35, "LuldAuctionCollar wire size");
static_assert(alignof(LuldAuctionCollar) == 1, "LuldAuctionCollar must have no alignment padding");
static_assert(std::is_standard_layout_v<LuldAuctionCollar>, "LuldAuctionCollar must be standard layout for offsetof");
static_assert(offsetof(LuldAuctionCollar, message_type) == 0, "LuldAuctionCollar::message_type offset");
static_assert(sizeof(LuldAuctionCollar::message_type) == 1, "LuldAuctionCollar::message_type length");
static_assert(offsetof(LuldAuctionCollar, stock_locate) == 1, "LuldAuctionCollar::stock_locate offset");
static_assert(sizeof(LuldAuctionCollar::stock_locate) == 2, "LuldAuctionCollar::stock_locate length");
static_assert(offsetof(LuldAuctionCollar, tracking_number) == 3, "LuldAuctionCollar::tracking_number offset");
static_assert(sizeof(LuldAuctionCollar::tracking_number) == 2, "LuldAuctionCollar::tracking_number length");
static_assert(offsetof(LuldAuctionCollar, timestamp) == 5, "LuldAuctionCollar::timestamp offset");
static_assert(sizeof(LuldAuctionCollar::timestamp) == 6, "LuldAuctionCollar::timestamp length");
static_assert(offsetof(LuldAuctionCollar, stock) == 11, "LuldAuctionCollar::stock offset");
static_assert(sizeof(LuldAuctionCollar::stock) == 8, "LuldAuctionCollar::stock length");
static_assert(offsetof(LuldAuctionCollar, auction_collar_reference_price) == 19, "LuldAuctionCollar::auction_collar_reference_price offset");
static_assert(sizeof(LuldAuctionCollar::auction_collar_reference_price) == 4, "LuldAuctionCollar::auction_collar_reference_price length");
static_assert(offsetof(LuldAuctionCollar, upper_auction_collar_price) == 23, "LuldAuctionCollar::upper_auction_collar_price offset");
static_assert(sizeof(LuldAuctionCollar::upper_auction_collar_price) == 4, "LuldAuctionCollar::upper_auction_collar_price length");
static_assert(offsetof(LuldAuctionCollar, lower_auction_collar_price) == 27, "LuldAuctionCollar::lower_auction_collar_price offset");
static_assert(sizeof(LuldAuctionCollar::lower_auction_collar_price) == 4, "LuldAuctionCollar::lower_auction_collar_price length");
static_assert(offsetof(LuldAuctionCollar, auction_collar_extension) == 31, "LuldAuctionCollar::auction_collar_extension offset");
static_assert(sizeof(LuldAuctionCollar::auction_collar_extension) == 4, "LuldAuctionCollar::auction_collar_extension length");

// 'h' -- Operational Halt (21 bytes)
struct OperationalHalt {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Alpha<1>   market_code;
    Alpha<1>   operational_halt_action;
};
static_assert(sizeof(OperationalHalt) == 21, "OperationalHalt wire size");
static_assert(alignof(OperationalHalt) == 1, "OperationalHalt must have no alignment padding");
static_assert(std::is_standard_layout_v<OperationalHalt>, "OperationalHalt must be standard layout for offsetof");
static_assert(offsetof(OperationalHalt, message_type) == 0, "OperationalHalt::message_type offset");
static_assert(sizeof(OperationalHalt::message_type) == 1, "OperationalHalt::message_type length");
static_assert(offsetof(OperationalHalt, stock_locate) == 1, "OperationalHalt::stock_locate offset");
static_assert(sizeof(OperationalHalt::stock_locate) == 2, "OperationalHalt::stock_locate length");
static_assert(offsetof(OperationalHalt, tracking_number) == 3, "OperationalHalt::tracking_number offset");
static_assert(sizeof(OperationalHalt::tracking_number) == 2, "OperationalHalt::tracking_number length");
static_assert(offsetof(OperationalHalt, timestamp) == 5, "OperationalHalt::timestamp offset");
static_assert(sizeof(OperationalHalt::timestamp) == 6, "OperationalHalt::timestamp length");
static_assert(offsetof(OperationalHalt, stock) == 11, "OperationalHalt::stock offset");
static_assert(sizeof(OperationalHalt::stock) == 8, "OperationalHalt::stock length");
static_assert(offsetof(OperationalHalt, market_code) == 19, "OperationalHalt::market_code offset");
static_assert(sizeof(OperationalHalt::market_code) == 1, "OperationalHalt::market_code length");
static_assert(offsetof(OperationalHalt, operational_halt_action) == 20, "OperationalHalt::operational_halt_action offset");
static_assert(sizeof(OperationalHalt::operational_halt_action) == 1, "OperationalHalt::operational_halt_action length");

// 'A' -- Add Order - No MPID Attribution Message (36 bytes)
struct AddOrder {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
    Alpha<1>   buy_sell_indicator;
    BeU32      shares;
    Alpha<8>   stock;
    Price4     price;
};
static_assert(sizeof(AddOrder) == 36, "AddOrder wire size");
static_assert(alignof(AddOrder) == 1, "AddOrder must have no alignment padding");
static_assert(std::is_standard_layout_v<AddOrder>, "AddOrder must be standard layout for offsetof");
static_assert(offsetof(AddOrder, message_type) == 0, "AddOrder::message_type offset");
static_assert(sizeof(AddOrder::message_type) == 1, "AddOrder::message_type length");
static_assert(offsetof(AddOrder, stock_locate) == 1, "AddOrder::stock_locate offset");
static_assert(sizeof(AddOrder::stock_locate) == 2, "AddOrder::stock_locate length");
static_assert(offsetof(AddOrder, tracking_number) == 3, "AddOrder::tracking_number offset");
static_assert(sizeof(AddOrder::tracking_number) == 2, "AddOrder::tracking_number length");
static_assert(offsetof(AddOrder, timestamp) == 5, "AddOrder::timestamp offset");
static_assert(sizeof(AddOrder::timestamp) == 6, "AddOrder::timestamp length");
static_assert(offsetof(AddOrder, order_reference_number) == 11, "AddOrder::order_reference_number offset");
static_assert(sizeof(AddOrder::order_reference_number) == 8, "AddOrder::order_reference_number length");
static_assert(offsetof(AddOrder, buy_sell_indicator) == 19, "AddOrder::buy_sell_indicator offset");
static_assert(sizeof(AddOrder::buy_sell_indicator) == 1, "AddOrder::buy_sell_indicator length");
static_assert(offsetof(AddOrder, shares) == 20, "AddOrder::shares offset");
static_assert(sizeof(AddOrder::shares) == 4, "AddOrder::shares length");
static_assert(offsetof(AddOrder, stock) == 24, "AddOrder::stock offset");
static_assert(sizeof(AddOrder::stock) == 8, "AddOrder::stock length");
static_assert(offsetof(AddOrder, price) == 32, "AddOrder::price offset");
static_assert(sizeof(AddOrder::price) == 4, "AddOrder::price length");

// 'F' -- Add Order - MPID Attribution Message (40 bytes)
struct AddOrderWithMpid {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
    Alpha<1>   buy_sell_indicator;
    BeU32      shares;
    Alpha<8>   stock;
    Price4     price;
    Alpha<4>   attribution;
};
static_assert(sizeof(AddOrderWithMpid) == 40, "AddOrderWithMpid wire size");
static_assert(alignof(AddOrderWithMpid) == 1, "AddOrderWithMpid must have no alignment padding");
static_assert(std::is_standard_layout_v<AddOrderWithMpid>, "AddOrderWithMpid must be standard layout for offsetof");
static_assert(offsetof(AddOrderWithMpid, message_type) == 0, "AddOrderWithMpid::message_type offset");
static_assert(sizeof(AddOrderWithMpid::message_type) == 1, "AddOrderWithMpid::message_type length");
static_assert(offsetof(AddOrderWithMpid, stock_locate) == 1, "AddOrderWithMpid::stock_locate offset");
static_assert(sizeof(AddOrderWithMpid::stock_locate) == 2, "AddOrderWithMpid::stock_locate length");
static_assert(offsetof(AddOrderWithMpid, tracking_number) == 3, "AddOrderWithMpid::tracking_number offset");
static_assert(sizeof(AddOrderWithMpid::tracking_number) == 2, "AddOrderWithMpid::tracking_number length");
static_assert(offsetof(AddOrderWithMpid, timestamp) == 5, "AddOrderWithMpid::timestamp offset");
static_assert(sizeof(AddOrderWithMpid::timestamp) == 6, "AddOrderWithMpid::timestamp length");
static_assert(offsetof(AddOrderWithMpid, order_reference_number) == 11, "AddOrderWithMpid::order_reference_number offset");
static_assert(sizeof(AddOrderWithMpid::order_reference_number) == 8, "AddOrderWithMpid::order_reference_number length");
static_assert(offsetof(AddOrderWithMpid, buy_sell_indicator) == 19, "AddOrderWithMpid::buy_sell_indicator offset");
static_assert(sizeof(AddOrderWithMpid::buy_sell_indicator) == 1, "AddOrderWithMpid::buy_sell_indicator length");
static_assert(offsetof(AddOrderWithMpid, shares) == 20, "AddOrderWithMpid::shares offset");
static_assert(sizeof(AddOrderWithMpid::shares) == 4, "AddOrderWithMpid::shares length");
static_assert(offsetof(AddOrderWithMpid, stock) == 24, "AddOrderWithMpid::stock offset");
static_assert(sizeof(AddOrderWithMpid::stock) == 8, "AddOrderWithMpid::stock length");
static_assert(offsetof(AddOrderWithMpid, price) == 32, "AddOrderWithMpid::price offset");
static_assert(sizeof(AddOrderWithMpid::price) == 4, "AddOrderWithMpid::price length");
static_assert(offsetof(AddOrderWithMpid, attribution) == 36, "AddOrderWithMpid::attribution offset");
static_assert(sizeof(AddOrderWithMpid::attribution) == 4, "AddOrderWithMpid::attribution length");

// 'E' -- Add Order - Order Executed Message (31 bytes)
struct OrderExecuted {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
    BeU32      executed_shares;
    BeU64      match_number;
};
static_assert(sizeof(OrderExecuted) == 31, "OrderExecuted wire size");
static_assert(alignof(OrderExecuted) == 1, "OrderExecuted must have no alignment padding");
static_assert(std::is_standard_layout_v<OrderExecuted>, "OrderExecuted must be standard layout for offsetof");
static_assert(offsetof(OrderExecuted, message_type) == 0, "OrderExecuted::message_type offset");
static_assert(sizeof(OrderExecuted::message_type) == 1, "OrderExecuted::message_type length");
static_assert(offsetof(OrderExecuted, stock_locate) == 1, "OrderExecuted::stock_locate offset");
static_assert(sizeof(OrderExecuted::stock_locate) == 2, "OrderExecuted::stock_locate length");
static_assert(offsetof(OrderExecuted, tracking_number) == 3, "OrderExecuted::tracking_number offset");
static_assert(sizeof(OrderExecuted::tracking_number) == 2, "OrderExecuted::tracking_number length");
static_assert(offsetof(OrderExecuted, timestamp) == 5, "OrderExecuted::timestamp offset");
static_assert(sizeof(OrderExecuted::timestamp) == 6, "OrderExecuted::timestamp length");
static_assert(offsetof(OrderExecuted, order_reference_number) == 11, "OrderExecuted::order_reference_number offset");
static_assert(sizeof(OrderExecuted::order_reference_number) == 8, "OrderExecuted::order_reference_number length");
static_assert(offsetof(OrderExecuted, executed_shares) == 19, "OrderExecuted::executed_shares offset");
static_assert(sizeof(OrderExecuted::executed_shares) == 4, "OrderExecuted::executed_shares length");
static_assert(offsetof(OrderExecuted, match_number) == 23, "OrderExecuted::match_number offset");
static_assert(sizeof(OrderExecuted::match_number) == 8, "OrderExecuted::match_number length");

// 'C' -- Add Order -Order Executed with Price Message (36 bytes)
struct OrderExecutedWithPrice {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
    BeU32      executed_shares;
    BeU64      match_number;
    Alpha<1>   printable;
    Price4     execution_price;
};
static_assert(sizeof(OrderExecutedWithPrice) == 36, "OrderExecutedWithPrice wire size");
static_assert(alignof(OrderExecutedWithPrice) == 1, "OrderExecutedWithPrice must have no alignment padding");
static_assert(std::is_standard_layout_v<OrderExecutedWithPrice>, "OrderExecutedWithPrice must be standard layout for offsetof");
static_assert(offsetof(OrderExecutedWithPrice, message_type) == 0, "OrderExecutedWithPrice::message_type offset");
static_assert(sizeof(OrderExecutedWithPrice::message_type) == 1, "OrderExecutedWithPrice::message_type length");
static_assert(offsetof(OrderExecutedWithPrice, stock_locate) == 1, "OrderExecutedWithPrice::stock_locate offset");
static_assert(sizeof(OrderExecutedWithPrice::stock_locate) == 2, "OrderExecutedWithPrice::stock_locate length");
static_assert(offsetof(OrderExecutedWithPrice, tracking_number) == 3, "OrderExecutedWithPrice::tracking_number offset");
static_assert(sizeof(OrderExecutedWithPrice::tracking_number) == 2, "OrderExecutedWithPrice::tracking_number length");
static_assert(offsetof(OrderExecutedWithPrice, timestamp) == 5, "OrderExecutedWithPrice::timestamp offset");
static_assert(sizeof(OrderExecutedWithPrice::timestamp) == 6, "OrderExecutedWithPrice::timestamp length");
static_assert(offsetof(OrderExecutedWithPrice, order_reference_number) == 11, "OrderExecutedWithPrice::order_reference_number offset");
static_assert(sizeof(OrderExecutedWithPrice::order_reference_number) == 8, "OrderExecutedWithPrice::order_reference_number length");
static_assert(offsetof(OrderExecutedWithPrice, executed_shares) == 19, "OrderExecutedWithPrice::executed_shares offset");
static_assert(sizeof(OrderExecutedWithPrice::executed_shares) == 4, "OrderExecutedWithPrice::executed_shares length");
static_assert(offsetof(OrderExecutedWithPrice, match_number) == 23, "OrderExecutedWithPrice::match_number offset");
static_assert(sizeof(OrderExecutedWithPrice::match_number) == 8, "OrderExecutedWithPrice::match_number length");
static_assert(offsetof(OrderExecutedWithPrice, printable) == 31, "OrderExecutedWithPrice::printable offset");
static_assert(sizeof(OrderExecutedWithPrice::printable) == 1, "OrderExecutedWithPrice::printable length");
static_assert(offsetof(OrderExecutedWithPrice, execution_price) == 32, "OrderExecutedWithPrice::execution_price offset");
static_assert(sizeof(OrderExecutedWithPrice::execution_price) == 4, "OrderExecutedWithPrice::execution_price length");

// 'X' -- Order Cancel Message (23 bytes)
struct OrderCancel {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
    BeU32      cancelled_shares;
};
static_assert(sizeof(OrderCancel) == 23, "OrderCancel wire size");
static_assert(alignof(OrderCancel) == 1, "OrderCancel must have no alignment padding");
static_assert(std::is_standard_layout_v<OrderCancel>, "OrderCancel must be standard layout for offsetof");
static_assert(offsetof(OrderCancel, message_type) == 0, "OrderCancel::message_type offset");
static_assert(sizeof(OrderCancel::message_type) == 1, "OrderCancel::message_type length");
static_assert(offsetof(OrderCancel, stock_locate) == 1, "OrderCancel::stock_locate offset");
static_assert(sizeof(OrderCancel::stock_locate) == 2, "OrderCancel::stock_locate length");
static_assert(offsetof(OrderCancel, tracking_number) == 3, "OrderCancel::tracking_number offset");
static_assert(sizeof(OrderCancel::tracking_number) == 2, "OrderCancel::tracking_number length");
static_assert(offsetof(OrderCancel, timestamp) == 5, "OrderCancel::timestamp offset");
static_assert(sizeof(OrderCancel::timestamp) == 6, "OrderCancel::timestamp length");
static_assert(offsetof(OrderCancel, order_reference_number) == 11, "OrderCancel::order_reference_number offset");
static_assert(sizeof(OrderCancel::order_reference_number) == 8, "OrderCancel::order_reference_number length");
static_assert(offsetof(OrderCancel, cancelled_shares) == 19, "OrderCancel::cancelled_shares offset");
static_assert(sizeof(OrderCancel::cancelled_shares) == 4, "OrderCancel::cancelled_shares length");

// 'D' -- Order Delete Message (19 bytes)
struct OrderDelete {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
};
static_assert(sizeof(OrderDelete) == 19, "OrderDelete wire size");
static_assert(alignof(OrderDelete) == 1, "OrderDelete must have no alignment padding");
static_assert(std::is_standard_layout_v<OrderDelete>, "OrderDelete must be standard layout for offsetof");
static_assert(offsetof(OrderDelete, message_type) == 0, "OrderDelete::message_type offset");
static_assert(sizeof(OrderDelete::message_type) == 1, "OrderDelete::message_type length");
static_assert(offsetof(OrderDelete, stock_locate) == 1, "OrderDelete::stock_locate offset");
static_assert(sizeof(OrderDelete::stock_locate) == 2, "OrderDelete::stock_locate length");
static_assert(offsetof(OrderDelete, tracking_number) == 3, "OrderDelete::tracking_number offset");
static_assert(sizeof(OrderDelete::tracking_number) == 2, "OrderDelete::tracking_number length");
static_assert(offsetof(OrderDelete, timestamp) == 5, "OrderDelete::timestamp offset");
static_assert(sizeof(OrderDelete::timestamp) == 6, "OrderDelete::timestamp length");
static_assert(offsetof(OrderDelete, order_reference_number) == 11, "OrderDelete::order_reference_number offset");
static_assert(sizeof(OrderDelete::order_reference_number) == 8, "OrderDelete::order_reference_number length");

// 'U' -- Order Replace Message (35 bytes)
struct OrderReplace {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      original_order_reference_number;
    BeU64      new_order_reference_number;
    BeU32      shares;
    Price4     price;
};
static_assert(sizeof(OrderReplace) == 35, "OrderReplace wire size");
static_assert(alignof(OrderReplace) == 1, "OrderReplace must have no alignment padding");
static_assert(std::is_standard_layout_v<OrderReplace>, "OrderReplace must be standard layout for offsetof");
static_assert(offsetof(OrderReplace, message_type) == 0, "OrderReplace::message_type offset");
static_assert(sizeof(OrderReplace::message_type) == 1, "OrderReplace::message_type length");
static_assert(offsetof(OrderReplace, stock_locate) == 1, "OrderReplace::stock_locate offset");
static_assert(sizeof(OrderReplace::stock_locate) == 2, "OrderReplace::stock_locate length");
static_assert(offsetof(OrderReplace, tracking_number) == 3, "OrderReplace::tracking_number offset");
static_assert(sizeof(OrderReplace::tracking_number) == 2, "OrderReplace::tracking_number length");
static_assert(offsetof(OrderReplace, timestamp) == 5, "OrderReplace::timestamp offset");
static_assert(sizeof(OrderReplace::timestamp) == 6, "OrderReplace::timestamp length");
static_assert(offsetof(OrderReplace, original_order_reference_number) == 11, "OrderReplace::original_order_reference_number offset");
static_assert(sizeof(OrderReplace::original_order_reference_number) == 8, "OrderReplace::original_order_reference_number length");
static_assert(offsetof(OrderReplace, new_order_reference_number) == 19, "OrderReplace::new_order_reference_number offset");
static_assert(sizeof(OrderReplace::new_order_reference_number) == 8, "OrderReplace::new_order_reference_number length");
static_assert(offsetof(OrderReplace, shares) == 27, "OrderReplace::shares offset");
static_assert(sizeof(OrderReplace::shares) == 4, "OrderReplace::shares length");
static_assert(offsetof(OrderReplace, price) == 31, "OrderReplace::price offset");
static_assert(sizeof(OrderReplace::price) == 4, "OrderReplace::price length");

// 'P' -- Trade Message (44 bytes)
struct TradeNonCross {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      order_reference_number;
    Alpha<1>   buy_sell_indicator;
    BeU32      shares;
    Alpha<8>   stock;
    Price4     price;
    BeU64      match_number;
};
static_assert(sizeof(TradeNonCross) == 44, "TradeNonCross wire size");
static_assert(alignof(TradeNonCross) == 1, "TradeNonCross must have no alignment padding");
static_assert(std::is_standard_layout_v<TradeNonCross>, "TradeNonCross must be standard layout for offsetof");
static_assert(offsetof(TradeNonCross, message_type) == 0, "TradeNonCross::message_type offset");
static_assert(sizeof(TradeNonCross::message_type) == 1, "TradeNonCross::message_type length");
static_assert(offsetof(TradeNonCross, stock_locate) == 1, "TradeNonCross::stock_locate offset");
static_assert(sizeof(TradeNonCross::stock_locate) == 2, "TradeNonCross::stock_locate length");
static_assert(offsetof(TradeNonCross, tracking_number) == 3, "TradeNonCross::tracking_number offset");
static_assert(sizeof(TradeNonCross::tracking_number) == 2, "TradeNonCross::tracking_number length");
static_assert(offsetof(TradeNonCross, timestamp) == 5, "TradeNonCross::timestamp offset");
static_assert(sizeof(TradeNonCross::timestamp) == 6, "TradeNonCross::timestamp length");
static_assert(offsetof(TradeNonCross, order_reference_number) == 11, "TradeNonCross::order_reference_number offset");
static_assert(sizeof(TradeNonCross::order_reference_number) == 8, "TradeNonCross::order_reference_number length");
static_assert(offsetof(TradeNonCross, buy_sell_indicator) == 19, "TradeNonCross::buy_sell_indicator offset");
static_assert(sizeof(TradeNonCross::buy_sell_indicator) == 1, "TradeNonCross::buy_sell_indicator length");
static_assert(offsetof(TradeNonCross, shares) == 20, "TradeNonCross::shares offset");
static_assert(sizeof(TradeNonCross::shares) == 4, "TradeNonCross::shares length");
static_assert(offsetof(TradeNonCross, stock) == 24, "TradeNonCross::stock offset");
static_assert(sizeof(TradeNonCross::stock) == 8, "TradeNonCross::stock length");
static_assert(offsetof(TradeNonCross, price) == 32, "TradeNonCross::price offset");
static_assert(sizeof(TradeNonCross::price) == 4, "TradeNonCross::price length");
static_assert(offsetof(TradeNonCross, match_number) == 36, "TradeNonCross::match_number offset");
static_assert(sizeof(TradeNonCross::match_number) == 8, "TradeNonCross::match_number length");

// 'Q' -- Cross Trade Message (40 bytes)
struct CrossTrade {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      shares;
    Alpha<8>   stock;
    Price4     cross_price;
    BeU64      match_number;
    Alpha<1>   cross_type;
};
static_assert(sizeof(CrossTrade) == 40, "CrossTrade wire size");
static_assert(alignof(CrossTrade) == 1, "CrossTrade must have no alignment padding");
static_assert(std::is_standard_layout_v<CrossTrade>, "CrossTrade must be standard layout for offsetof");
static_assert(offsetof(CrossTrade, message_type) == 0, "CrossTrade::message_type offset");
static_assert(sizeof(CrossTrade::message_type) == 1, "CrossTrade::message_type length");
static_assert(offsetof(CrossTrade, stock_locate) == 1, "CrossTrade::stock_locate offset");
static_assert(sizeof(CrossTrade::stock_locate) == 2, "CrossTrade::stock_locate length");
static_assert(offsetof(CrossTrade, tracking_number) == 3, "CrossTrade::tracking_number offset");
static_assert(sizeof(CrossTrade::tracking_number) == 2, "CrossTrade::tracking_number length");
static_assert(offsetof(CrossTrade, timestamp) == 5, "CrossTrade::timestamp offset");
static_assert(sizeof(CrossTrade::timestamp) == 6, "CrossTrade::timestamp length");
static_assert(offsetof(CrossTrade, shares) == 11, "CrossTrade::shares offset");
static_assert(sizeof(CrossTrade::shares) == 8, "CrossTrade::shares length");
static_assert(offsetof(CrossTrade, stock) == 19, "CrossTrade::stock offset");
static_assert(sizeof(CrossTrade::stock) == 8, "CrossTrade::stock length");
static_assert(offsetof(CrossTrade, cross_price) == 27, "CrossTrade::cross_price offset");
static_assert(sizeof(CrossTrade::cross_price) == 4, "CrossTrade::cross_price length");
static_assert(offsetof(CrossTrade, match_number) == 31, "CrossTrade::match_number offset");
static_assert(sizeof(CrossTrade::match_number) == 8, "CrossTrade::match_number length");
static_assert(offsetof(CrossTrade, cross_type) == 39, "CrossTrade::cross_type offset");
static_assert(sizeof(CrossTrade::cross_type) == 1, "CrossTrade::cross_type length");

// 'B' -- Broken Trade Message (19 bytes)
struct BrokenTrade {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      match_number;
};
static_assert(sizeof(BrokenTrade) == 19, "BrokenTrade wire size");
static_assert(alignof(BrokenTrade) == 1, "BrokenTrade must have no alignment padding");
static_assert(std::is_standard_layout_v<BrokenTrade>, "BrokenTrade must be standard layout for offsetof");
static_assert(offsetof(BrokenTrade, message_type) == 0, "BrokenTrade::message_type offset");
static_assert(sizeof(BrokenTrade::message_type) == 1, "BrokenTrade::message_type length");
static_assert(offsetof(BrokenTrade, stock_locate) == 1, "BrokenTrade::stock_locate offset");
static_assert(sizeof(BrokenTrade::stock_locate) == 2, "BrokenTrade::stock_locate length");
static_assert(offsetof(BrokenTrade, tracking_number) == 3, "BrokenTrade::tracking_number offset");
static_assert(sizeof(BrokenTrade::tracking_number) == 2, "BrokenTrade::tracking_number length");
static_assert(offsetof(BrokenTrade, timestamp) == 5, "BrokenTrade::timestamp offset");
static_assert(sizeof(BrokenTrade::timestamp) == 6, "BrokenTrade::timestamp length");
static_assert(offsetof(BrokenTrade, match_number) == 11, "BrokenTrade::match_number offset");
static_assert(sizeof(BrokenTrade::match_number) == 8, "BrokenTrade::match_number length");

// 'I' -- NOII Message (50 bytes)
struct Noii {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    BeU64      paired_shares;
    BeU64      imbalance_shares;
    Alpha<1>   imbalance_direction;
    Alpha<8>   stock;
    Price4     far_price;
    Price4     near_price;
    Price4     current_reference_price;
    Alpha<1>   cross_type;
    Alpha<1>   price_variation_indicator;
};
static_assert(sizeof(Noii) == 50, "Noii wire size");
static_assert(alignof(Noii) == 1, "Noii must have no alignment padding");
static_assert(std::is_standard_layout_v<Noii>, "Noii must be standard layout for offsetof");
static_assert(offsetof(Noii, message_type) == 0, "Noii::message_type offset");
static_assert(sizeof(Noii::message_type) == 1, "Noii::message_type length");
static_assert(offsetof(Noii, stock_locate) == 1, "Noii::stock_locate offset");
static_assert(sizeof(Noii::stock_locate) == 2, "Noii::stock_locate length");
static_assert(offsetof(Noii, tracking_number) == 3, "Noii::tracking_number offset");
static_assert(sizeof(Noii::tracking_number) == 2, "Noii::tracking_number length");
static_assert(offsetof(Noii, timestamp) == 5, "Noii::timestamp offset");
static_assert(sizeof(Noii::timestamp) == 6, "Noii::timestamp length");
static_assert(offsetof(Noii, paired_shares) == 11, "Noii::paired_shares offset");
static_assert(sizeof(Noii::paired_shares) == 8, "Noii::paired_shares length");
static_assert(offsetof(Noii, imbalance_shares) == 19, "Noii::imbalance_shares offset");
static_assert(sizeof(Noii::imbalance_shares) == 8, "Noii::imbalance_shares length");
static_assert(offsetof(Noii, imbalance_direction) == 27, "Noii::imbalance_direction offset");
static_assert(sizeof(Noii::imbalance_direction) == 1, "Noii::imbalance_direction length");
static_assert(offsetof(Noii, stock) == 28, "Noii::stock offset");
static_assert(sizeof(Noii::stock) == 8, "Noii::stock length");
static_assert(offsetof(Noii, far_price) == 36, "Noii::far_price offset");
static_assert(sizeof(Noii::far_price) == 4, "Noii::far_price length");
static_assert(offsetof(Noii, near_price) == 40, "Noii::near_price offset");
static_assert(sizeof(Noii::near_price) == 4, "Noii::near_price length");
static_assert(offsetof(Noii, current_reference_price) == 44, "Noii::current_reference_price offset");
static_assert(sizeof(Noii::current_reference_price) == 4, "Noii::current_reference_price length");
static_assert(offsetof(Noii, cross_type) == 48, "Noii::cross_type offset");
static_assert(sizeof(Noii::cross_type) == 1, "Noii::cross_type length");
static_assert(offsetof(Noii, price_variation_indicator) == 49, "Noii::price_variation_indicator offset");
static_assert(sizeof(Noii::price_variation_indicator) == 1, "Noii::price_variation_indicator length");

// 'N' -- Retail Interest message (20 bytes)
struct RetailPriceImprovement {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Alpha<1>   interest_flag;
};
static_assert(sizeof(RetailPriceImprovement) == 20, "RetailPriceImprovement wire size");
static_assert(alignof(RetailPriceImprovement) == 1, "RetailPriceImprovement must have no alignment padding");
static_assert(std::is_standard_layout_v<RetailPriceImprovement>, "RetailPriceImprovement must be standard layout for offsetof");
static_assert(offsetof(RetailPriceImprovement, message_type) == 0, "RetailPriceImprovement::message_type offset");
static_assert(sizeof(RetailPriceImprovement::message_type) == 1, "RetailPriceImprovement::message_type length");
static_assert(offsetof(RetailPriceImprovement, stock_locate) == 1, "RetailPriceImprovement::stock_locate offset");
static_assert(sizeof(RetailPriceImprovement::stock_locate) == 2, "RetailPriceImprovement::stock_locate length");
static_assert(offsetof(RetailPriceImprovement, tracking_number) == 3, "RetailPriceImprovement::tracking_number offset");
static_assert(sizeof(RetailPriceImprovement::tracking_number) == 2, "RetailPriceImprovement::tracking_number length");
static_assert(offsetof(RetailPriceImprovement, timestamp) == 5, "RetailPriceImprovement::timestamp offset");
static_assert(sizeof(RetailPriceImprovement::timestamp) == 6, "RetailPriceImprovement::timestamp length");
static_assert(offsetof(RetailPriceImprovement, stock) == 11, "RetailPriceImprovement::stock offset");
static_assert(sizeof(RetailPriceImprovement::stock) == 8, "RetailPriceImprovement::stock length");
static_assert(offsetof(RetailPriceImprovement, interest_flag) == 19, "RetailPriceImprovement::interest_flag offset");
static_assert(sizeof(RetailPriceImprovement::interest_flag) == 1, "RetailPriceImprovement::interest_flag length");

// 'O' -- Direct Listing with Capital Raise Message (48 bytes)
struct DirectListingWithCapitalRaise {
    Alpha<1>   message_type;
    BeU16      stock_locate;
    BeU16      tracking_number;
    BeU48      timestamp;
    Alpha<8>   stock;
    Alpha<1>   open_eligibility_status;
    Price4     minimum_allowable_price;
    Price4     maximum_allowable_price;
    Price4     near_execution_price;
    BeU64      near_execution_time;
    Price4     lower_price_range_collar;
    Price4     upper_price_range_collar;
};
static_assert(sizeof(DirectListingWithCapitalRaise) == 48, "DirectListingWithCapitalRaise wire size");
static_assert(alignof(DirectListingWithCapitalRaise) == 1, "DirectListingWithCapitalRaise must have no alignment padding");
static_assert(std::is_standard_layout_v<DirectListingWithCapitalRaise>, "DirectListingWithCapitalRaise must be standard layout for offsetof");
static_assert(offsetof(DirectListingWithCapitalRaise, message_type) == 0, "DirectListingWithCapitalRaise::message_type offset");
static_assert(sizeof(DirectListingWithCapitalRaise::message_type) == 1, "DirectListingWithCapitalRaise::message_type length");
static_assert(offsetof(DirectListingWithCapitalRaise, stock_locate) == 1, "DirectListingWithCapitalRaise::stock_locate offset");
static_assert(sizeof(DirectListingWithCapitalRaise::stock_locate) == 2, "DirectListingWithCapitalRaise::stock_locate length");
static_assert(offsetof(DirectListingWithCapitalRaise, tracking_number) == 3, "DirectListingWithCapitalRaise::tracking_number offset");
static_assert(sizeof(DirectListingWithCapitalRaise::tracking_number) == 2, "DirectListingWithCapitalRaise::tracking_number length");
static_assert(offsetof(DirectListingWithCapitalRaise, timestamp) == 5, "DirectListingWithCapitalRaise::timestamp offset");
static_assert(sizeof(DirectListingWithCapitalRaise::timestamp) == 6, "DirectListingWithCapitalRaise::timestamp length");
static_assert(offsetof(DirectListingWithCapitalRaise, stock) == 11, "DirectListingWithCapitalRaise::stock offset");
static_assert(sizeof(DirectListingWithCapitalRaise::stock) == 8, "DirectListingWithCapitalRaise::stock length");
static_assert(offsetof(DirectListingWithCapitalRaise, open_eligibility_status) == 19, "DirectListingWithCapitalRaise::open_eligibility_status offset");
static_assert(sizeof(DirectListingWithCapitalRaise::open_eligibility_status) == 1, "DirectListingWithCapitalRaise::open_eligibility_status length");
static_assert(offsetof(DirectListingWithCapitalRaise, minimum_allowable_price) == 20, "DirectListingWithCapitalRaise::minimum_allowable_price offset");
static_assert(sizeof(DirectListingWithCapitalRaise::minimum_allowable_price) == 4, "DirectListingWithCapitalRaise::minimum_allowable_price length");
static_assert(offsetof(DirectListingWithCapitalRaise, maximum_allowable_price) == 24, "DirectListingWithCapitalRaise::maximum_allowable_price offset");
static_assert(sizeof(DirectListingWithCapitalRaise::maximum_allowable_price) == 4, "DirectListingWithCapitalRaise::maximum_allowable_price length");
static_assert(offsetof(DirectListingWithCapitalRaise, near_execution_price) == 28, "DirectListingWithCapitalRaise::near_execution_price offset");
static_assert(sizeof(DirectListingWithCapitalRaise::near_execution_price) == 4, "DirectListingWithCapitalRaise::near_execution_price length");
static_assert(offsetof(DirectListingWithCapitalRaise, near_execution_time) == 32, "DirectListingWithCapitalRaise::near_execution_time offset");
static_assert(sizeof(DirectListingWithCapitalRaise::near_execution_time) == 8, "DirectListingWithCapitalRaise::near_execution_time length");
static_assert(offsetof(DirectListingWithCapitalRaise, lower_price_range_collar) == 40, "DirectListingWithCapitalRaise::lower_price_range_collar offset");
static_assert(sizeof(DirectListingWithCapitalRaise::lower_price_range_collar) == 4, "DirectListingWithCapitalRaise::lower_price_range_collar length");
static_assert(offsetof(DirectListingWithCapitalRaise, upper_price_range_collar) == 44, "DirectListingWithCapitalRaise::upper_price_range_collar offset");
static_assert(sizeof(DirectListingWithCapitalRaise::upper_price_range_collar) == 4, "DirectListingWithCapitalRaise::upper_price_range_collar length");

// Declared body length for a message type, or 0 if the type is unknown.
// The framing layer cross-checks this against the length prefix on the wire,
// which turns the real feed into a test of every size above.
[[nodiscard]] constexpr std::size_t message_length(char type) noexcept {
    switch (type) {
        case 'S': return sizeof(SystemEvent);
        case 'R': return sizeof(StockDirectory);
        case 'H': return sizeof(StockTradingAction);
        case 'Y': return sizeof(RegShoRestriction);
        case 'L': return sizeof(MarketParticipantPosition);
        case 'V': return sizeof(MwcbDeclineLevel);
        case 'W': return sizeof(MwcbStatus);
        case 'K': return sizeof(IpoQuotingPeriodUpdate);
        case 'J': return sizeof(LuldAuctionCollar);
        case 'h': return sizeof(OperationalHalt);
        case 'A': return sizeof(AddOrder);
        case 'F': return sizeof(AddOrderWithMpid);
        case 'E': return sizeof(OrderExecuted);
        case 'C': return sizeof(OrderExecutedWithPrice);
        case 'X': return sizeof(OrderCancel);
        case 'D': return sizeof(OrderDelete);
        case 'U': return sizeof(OrderReplace);
        case 'P': return sizeof(TradeNonCross);
        case 'Q': return sizeof(CrossTrade);
        case 'B': return sizeof(BrokenTrade);
        case 'I': return sizeof(Noii);
        case 'N': return sizeof(RetailPriceImprovement);
        case 'O': return sizeof(DirectListingWithCapitalRaise);
        default: return 0;
    }
}

// Short name for a message type, for reporting. "unknown" if not a type.
[[nodiscard]] constexpr const char* type_name(char type) noexcept {
    switch (type) {
        case 'S': return "SystemEvent";
        case 'R': return "StockDirectory";
        case 'H': return "StockTradingAction";
        case 'Y': return "RegShoRestriction";
        case 'L': return "MarketParticipantPosition";
        case 'V': return "MwcbDeclineLevel";
        case 'W': return "MwcbStatus";
        case 'K': return "IpoQuotingPeriodUpdate";
        case 'J': return "LuldAuctionCollar";
        case 'h': return "OperationalHalt";
        case 'A': return "AddOrder";
        case 'F': return "AddOrderWithMpid";
        case 'E': return "OrderExecuted";
        case 'C': return "OrderExecutedWithPrice";
        case 'X': return "OrderCancel";
        case 'D': return "OrderDelete";
        case 'U': return "OrderReplace";
        case 'P': return "TradeNonCross";
        case 'Q': return "CrossTrade";
        case 'B': return "BrokenTrade";
        case 'I': return "Noii";
        case 'N': return "RetailPriceImprovement";
        case 'O': return "DirectListingWithCapitalRaise";
        default: return "unknown";
    }
}

[[nodiscard]] constexpr bool is_known_type(char type) noexcept {
    return message_length(type) != 0;
}

}  // namespace itch::wire
