// Generated by tools/gen_wire.py. Do not edit by hand.
//
// One view per message type. A view is a bare pointer into the frame; each
// accessor decodes exactly the field asked for, at an offset taken from the
// layout struct in messages.hpp. Fields a handler never reads are never
// byteswapped, and nothing is copied.
//
// dispatch() calls handler.on_xxx(view) for the message it was given, and
// skips any handler method that does not exist, so a handler implements only
// the messages it cares about. No virtual calls, no empty overrides.
#pragma once

#include <cstddef>
#include <string_view>

#include "itch/core/endian.hpp"
#include "itch/core/types.hpp"
#include "itch/wire/messages.hpp"

namespace itch::wire {

// Alpha fields are left-justified and space padded. Returns the field with
// the padding removed.
[[nodiscard]] inline std::string_view trim_alpha(std::string_view s) noexcept {
    while (!s.empty() && s.back() == ' ') {
        s.remove_suffix(1);
    }
    return s;
}

// 'S' -- System Event Message
class SystemEventView {
public:
    static constexpr char kType = 'S';
    static constexpr std::size_t kSize = sizeof(SystemEvent);

    explicit constexpr SystemEventView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(SystemEvent, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(SystemEvent, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(SystemEvent, timestamp)));
    }
    [[nodiscard]] char event_code() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(SystemEvent, event_code)));
    }

private:
    const std::byte* p_;
};

// 'R' -- Stock Directory Message
class StockDirectoryView {
public:
    static constexpr char kType = 'R';
    static constexpr std::size_t kSize = sizeof(StockDirectory);

    explicit constexpr StockDirectoryView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(StockDirectory, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(StockDirectory, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(StockDirectory, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(StockDirectory, stock),
                                8);
    }
    [[nodiscard]] char market_category() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, market_category)));
    }
    [[nodiscard]] char financial_status_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, financial_status_indicator)));
    }
    [[nodiscard]] u32 round_lot_size() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(StockDirectory, round_lot_size)));
    }
    [[nodiscard]] char round_lots_only() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, round_lots_only)));
    }
    [[nodiscard]] char issue_classification() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, issue_classification)));
    }
    [[nodiscard]] std::string_view issue_sub_type() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(StockDirectory, issue_sub_type),
                                2);
    }
    [[nodiscard]] char authenticity() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, authenticity)));
    }
    [[nodiscard]] char short_sale_threshold_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, short_sale_threshold_indicator)));
    }
    [[nodiscard]] char ipo_flag() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, ipo_flag)));
    }
    [[nodiscard]] char luld_reference_price_tier() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, luld_reference_price_tier)));
    }
    [[nodiscard]] char etp_flag() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, etp_flag)));
    }
    [[nodiscard]] u32 etp_leverage_factor() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(StockDirectory, etp_leverage_factor)));
    }
    [[nodiscard]] char inverse_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockDirectory, inverse_indicator)));
    }

private:
    const std::byte* p_;
};

// 'H' -- Stock Trading Action Message
class StockTradingActionView {
public:
    static constexpr char kType = 'H';
    static constexpr std::size_t kSize = sizeof(StockTradingAction);

    explicit constexpr StockTradingActionView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(StockTradingAction, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(StockTradingAction, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(StockTradingAction, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(StockTradingAction, stock),
                                8);
    }
    [[nodiscard]] char trading_state() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockTradingAction, trading_state)));
    }
    [[nodiscard]] char reserved() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(StockTradingAction, reserved)));
    }
    [[nodiscard]] std::string_view reason() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(StockTradingAction, reason),
                                4);
    }

private:
    const std::byte* p_;
};

// 'Y' -- Reg SHO Short Sale Price Test Restricted Indicator
class RegShoRestrictionView {
public:
    static constexpr char kType = 'Y';
    static constexpr std::size_t kSize = sizeof(RegShoRestriction);

    explicit constexpr RegShoRestrictionView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(RegShoRestriction, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(RegShoRestriction, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(RegShoRestriction, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(RegShoRestriction, stock),
                                8);
    }
    [[nodiscard]] char reg_sho_action() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(RegShoRestriction, reg_sho_action)));
    }

private:
    const std::byte* p_;
};

// 'L' -- Market Participant Position message
class MarketParticipantPositionView {
public:
    static constexpr char kType = 'L';
    static constexpr std::size_t kSize = sizeof(MarketParticipantPosition);

    explicit constexpr MarketParticipantPositionView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(MarketParticipantPosition, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(MarketParticipantPosition, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(MarketParticipantPosition, timestamp)));
    }
    [[nodiscard]] std::string_view mpid() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(MarketParticipantPosition, mpid),
                                4);
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(MarketParticipantPosition, stock),
                                8);
    }
    [[nodiscard]] char primary_market() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(MarketParticipantPosition, primary_market)));
    }
    [[nodiscard]] char market_maker_mode() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(MarketParticipantPosition, market_maker_mode)));
    }
    [[nodiscard]] char market_participant_state() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(MarketParticipantPosition, market_participant_state)));
    }

private:
    const std::byte* p_;
};

// 'V' -- Market wide circuit breaker Decline Level Message
class MwcbDeclineLevelView {
public:
    static constexpr char kType = 'V';
    static constexpr std::size_t kSize = sizeof(MwcbDeclineLevel);

    explicit constexpr MwcbDeclineLevelView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(MwcbDeclineLevel, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(MwcbDeclineLevel, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(MwcbDeclineLevel, timestamp)));
    }
    [[nodiscard]] u64 level_1() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(MwcbDeclineLevel, level_1)));
    }
    [[nodiscard]] u64 level_2() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(MwcbDeclineLevel, level_2)));
    }
    [[nodiscard]] u64 level_3() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(MwcbDeclineLevel, level_3)));
    }

private:
    const std::byte* p_;
};

// 'W' -- Market-Wide Circuit Breaker Status message
class MwcbStatusView {
public:
    static constexpr char kType = 'W';
    static constexpr std::size_t kSize = sizeof(MwcbStatus);

    explicit constexpr MwcbStatusView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(MwcbStatus, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(MwcbStatus, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(MwcbStatus, timestamp)));
    }
    [[nodiscard]] char breached_level() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(MwcbStatus, breached_level)));
    }

private:
    const std::byte* p_;
};

// 'K' -- IPO Quoting Period Update Message
class IpoQuotingPeriodUpdateView {
public:
    static constexpr char kType = 'K';
    static constexpr std::size_t kSize = sizeof(IpoQuotingPeriodUpdate);

    explicit constexpr IpoQuotingPeriodUpdateView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(IpoQuotingPeriodUpdate, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(IpoQuotingPeriodUpdate, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(IpoQuotingPeriodUpdate, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(IpoQuotingPeriodUpdate, stock),
                                8);
    }
    [[nodiscard]] u32 ipo_quotation_release_time() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(IpoQuotingPeriodUpdate, ipo_quotation_release_time)));
    }
    [[nodiscard]] char ipo_quotation_release_qualifier() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(IpoQuotingPeriodUpdate, ipo_quotation_release_qualifier)));
    }
    [[nodiscard]] Price ipo_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(IpoQuotingPeriodUpdate, ipo_price)));
    }

private:
    const std::byte* p_;
};

// 'J' -- LULD Auction Collar
class LuldAuctionCollarView {
public:
    static constexpr char kType = 'J';
    static constexpr std::size_t kSize = sizeof(LuldAuctionCollar);

    explicit constexpr LuldAuctionCollarView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(LuldAuctionCollar, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(LuldAuctionCollar, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(LuldAuctionCollar, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(LuldAuctionCollar, stock),
                                8);
    }
    [[nodiscard]] Price auction_collar_reference_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(LuldAuctionCollar, auction_collar_reference_price)));
    }
    [[nodiscard]] Price upper_auction_collar_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(LuldAuctionCollar, upper_auction_collar_price)));
    }
    [[nodiscard]] Price lower_auction_collar_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(LuldAuctionCollar, lower_auction_collar_price)));
    }
    [[nodiscard]] u32 auction_collar_extension() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(LuldAuctionCollar, auction_collar_extension)));
    }

private:
    const std::byte* p_;
};

// 'h' -- Operational Halt
class OperationalHaltView {
public:
    static constexpr char kType = 'h';
    static constexpr std::size_t kSize = sizeof(OperationalHalt);

    explicit constexpr OperationalHaltView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OperationalHalt, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OperationalHalt, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(OperationalHalt, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(OperationalHalt, stock),
                                8);
    }
    [[nodiscard]] char market_code() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(OperationalHalt, market_code)));
    }
    [[nodiscard]] char operational_halt_action() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(OperationalHalt, operational_halt_action)));
    }

private:
    const std::byte* p_;
};

// 'A' -- Add Order - No MPID Attribution Message
class AddOrderView {
public:
    static constexpr char kType = 'A';
    static constexpr std::size_t kSize = sizeof(AddOrder);

    explicit constexpr AddOrderView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(AddOrder, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(AddOrder, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(AddOrder, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(AddOrder, order_reference_number)));
    }
    [[nodiscard]] char buy_sell_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(AddOrder, buy_sell_indicator)));
    }
    [[nodiscard]] u32 shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(AddOrder, shares)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(AddOrder, stock),
                                8);
    }
    [[nodiscard]] Price price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(AddOrder, price)));
    }

private:
    const std::byte* p_;
};

// 'F' -- Add Order - MPID Attribution Message
class AddOrderWithMpidView {
public:
    static constexpr char kType = 'F';
    static constexpr std::size_t kSize = sizeof(AddOrderWithMpid);

    explicit constexpr AddOrderWithMpidView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(AddOrderWithMpid, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(AddOrderWithMpid, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(AddOrderWithMpid, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(AddOrderWithMpid, order_reference_number)));
    }
    [[nodiscard]] char buy_sell_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(AddOrderWithMpid, buy_sell_indicator)));
    }
    [[nodiscard]] u32 shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(AddOrderWithMpid, shares)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(AddOrderWithMpid, stock),
                                8);
    }
    [[nodiscard]] Price price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(AddOrderWithMpid, price)));
    }
    [[nodiscard]] std::string_view attribution() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(AddOrderWithMpid, attribution),
                                4);
    }

private:
    const std::byte* p_;
};

// 'E' -- Add Order - Order Executed Message
class OrderExecutedView {
public:
    static constexpr char kType = 'E';
    static constexpr std::size_t kSize = sizeof(OrderExecuted);

    explicit constexpr OrderExecutedView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderExecuted, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderExecuted, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(OrderExecuted, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderExecuted, order_reference_number)));
    }
    [[nodiscard]] u32 executed_shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(OrderExecuted, executed_shares)));
    }
    [[nodiscard]] u64 match_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderExecuted, match_number)));
    }

private:
    const std::byte* p_;
};

// 'C' -- Add Order -Order Executed with Price Message
class OrderExecutedWithPriceView {
public:
    static constexpr char kType = 'C';
    static constexpr std::size_t kSize = sizeof(OrderExecutedWithPrice);

    explicit constexpr OrderExecutedWithPriceView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderExecutedWithPrice, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderExecutedWithPrice, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(OrderExecutedWithPrice, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderExecutedWithPrice, order_reference_number)));
    }
    [[nodiscard]] u32 executed_shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(OrderExecutedWithPrice, executed_shares)));
    }
    [[nodiscard]] u64 match_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderExecutedWithPrice, match_number)));
    }
    [[nodiscard]] char printable() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(OrderExecutedWithPrice, printable)));
    }
    [[nodiscard]] Price execution_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(OrderExecutedWithPrice, execution_price)));
    }

private:
    const std::byte* p_;
};

// 'X' -- Order Cancel Message
class OrderCancelView {
public:
    static constexpr char kType = 'X';
    static constexpr std::size_t kSize = sizeof(OrderCancel);

    explicit constexpr OrderCancelView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderCancel, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderCancel, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(OrderCancel, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderCancel, order_reference_number)));
    }
    [[nodiscard]] u32 cancelled_shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(OrderCancel, cancelled_shares)));
    }

private:
    const std::byte* p_;
};

// 'D' -- Order Delete Message
class OrderDeleteView {
public:
    static constexpr char kType = 'D';
    static constexpr std::size_t kSize = sizeof(OrderDelete);

    explicit constexpr OrderDeleteView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderDelete, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderDelete, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(OrderDelete, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderDelete, order_reference_number)));
    }

private:
    const std::byte* p_;
};

// 'U' -- Order Replace Message
class OrderReplaceView {
public:
    static constexpr char kType = 'U';
    static constexpr std::size_t kSize = sizeof(OrderReplace);

    explicit constexpr OrderReplaceView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderReplace, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(OrderReplace, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(OrderReplace, timestamp)));
    }
    [[nodiscard]] u64 original_order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderReplace, original_order_reference_number)));
    }
    [[nodiscard]] u64 new_order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(OrderReplace, new_order_reference_number)));
    }
    [[nodiscard]] u32 shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(OrderReplace, shares)));
    }
    [[nodiscard]] Price price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(OrderReplace, price)));
    }

private:
    const std::byte* p_;
};

// 'P' -- Trade Message
class TradeNonCrossView {
public:
    static constexpr char kType = 'P';
    static constexpr std::size_t kSize = sizeof(TradeNonCross);

    explicit constexpr TradeNonCrossView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(TradeNonCross, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(TradeNonCross, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(TradeNonCross, timestamp)));
    }
    [[nodiscard]] u64 order_reference_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(TradeNonCross, order_reference_number)));
    }
    [[nodiscard]] char buy_sell_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(TradeNonCross, buy_sell_indicator)));
    }
    [[nodiscard]] u32 shares() const noexcept {
        return static_cast<u32>(load_be<u32>(p_ + offsetof(TradeNonCross, shares)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(TradeNonCross, stock),
                                8);
    }
    [[nodiscard]] Price price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(TradeNonCross, price)));
    }
    [[nodiscard]] u64 match_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(TradeNonCross, match_number)));
    }

private:
    const std::byte* p_;
};

// 'Q' -- Cross Trade Message
class CrossTradeView {
public:
    static constexpr char kType = 'Q';
    static constexpr std::size_t kSize = sizeof(CrossTrade);

    explicit constexpr CrossTradeView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(CrossTrade, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(CrossTrade, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(CrossTrade, timestamp)));
    }
    [[nodiscard]] u64 shares() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(CrossTrade, shares)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(CrossTrade, stock),
                                8);
    }
    [[nodiscard]] Price cross_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(CrossTrade, cross_price)));
    }
    [[nodiscard]] u64 match_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(CrossTrade, match_number)));
    }
    [[nodiscard]] char cross_type() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(CrossTrade, cross_type)));
    }

private:
    const std::byte* p_;
};

// 'B' -- Broken Trade Message
class BrokenTradeView {
public:
    static constexpr char kType = 'B';
    static constexpr std::size_t kSize = sizeof(BrokenTrade);

    explicit constexpr BrokenTradeView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(BrokenTrade, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(BrokenTrade, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(BrokenTrade, timestamp)));
    }
    [[nodiscard]] u64 match_number() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(BrokenTrade, match_number)));
    }

private:
    const std::byte* p_;
};

// 'I' -- NOII Message
class NoiiView {
public:
    static constexpr char kType = 'I';
    static constexpr std::size_t kSize = sizeof(Noii);

    explicit constexpr NoiiView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(Noii, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(Noii, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(Noii, timestamp)));
    }
    [[nodiscard]] u64 paired_shares() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(Noii, paired_shares)));
    }
    [[nodiscard]] u64 imbalance_shares() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(Noii, imbalance_shares)));
    }
    [[nodiscard]] char imbalance_direction() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(Noii, imbalance_direction)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(Noii, stock),
                                8);
    }
    [[nodiscard]] Price far_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(Noii, far_price)));
    }
    [[nodiscard]] Price near_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(Noii, near_price)));
    }
    [[nodiscard]] Price current_reference_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(Noii, current_reference_price)));
    }
    [[nodiscard]] char cross_type() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(Noii, cross_type)));
    }
    [[nodiscard]] char price_variation_indicator() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(Noii, price_variation_indicator)));
    }

private:
    const std::byte* p_;
};

// 'N' -- Retail Interest message
class RetailPriceImprovementView {
public:
    static constexpr char kType = 'N';
    static constexpr std::size_t kSize = sizeof(RetailPriceImprovement);

    explicit constexpr RetailPriceImprovementView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(RetailPriceImprovement, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(RetailPriceImprovement, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(RetailPriceImprovement, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(RetailPriceImprovement, stock),
                                8);
    }
    [[nodiscard]] char interest_flag() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(RetailPriceImprovement, interest_flag)));
    }

private:
    const std::byte* p_;
};

// 'O' -- Direct Listing with Capital Raise Message
class DirectListingWithCapitalRaiseView {
public:
    static constexpr char kType = 'O';
    static constexpr std::size_t kSize = sizeof(DirectListingWithCapitalRaise);

    explicit constexpr DirectListingWithCapitalRaiseView(const std::byte* p) noexcept : p_(p) {}

    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }

    [[nodiscard]] u16 stock_locate() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(DirectListingWithCapitalRaise, stock_locate)));
    }
    [[nodiscard]] u16 tracking_number() const noexcept {
        return static_cast<u16>(load_be<u16>(p_ + offsetof(DirectListingWithCapitalRaise, tracking_number)));
    }
    [[nodiscard]] Timestamp timestamp() const noexcept {
        return static_cast<Timestamp>(load_be48(p_ + offsetof(DirectListingWithCapitalRaise, timestamp)));
    }
    [[nodiscard]] std::string_view stock() const noexcept {
        return std::string_view(reinterpret_cast<const char*>(p_) +
                                    offsetof(DirectListingWithCapitalRaise, stock),
                                8);
    }
    [[nodiscard]] char open_eligibility_status() const noexcept {
        return static_cast<char>(load_be<u8>(p_ + offsetof(DirectListingWithCapitalRaise, open_eligibility_status)));
    }
    [[nodiscard]] Price minimum_allowable_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(DirectListingWithCapitalRaise, minimum_allowable_price)));
    }
    [[nodiscard]] Price maximum_allowable_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(DirectListingWithCapitalRaise, maximum_allowable_price)));
    }
    [[nodiscard]] Price near_execution_price() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(DirectListingWithCapitalRaise, near_execution_price)));
    }
    [[nodiscard]] u64 near_execution_time() const noexcept {
        return static_cast<u64>(load_be<u64>(p_ + offsetof(DirectListingWithCapitalRaise, near_execution_time)));
    }
    [[nodiscard]] Price lower_price_range_collar() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(DirectListingWithCapitalRaise, lower_price_range_collar)));
    }
    [[nodiscard]] Price upper_price_range_collar() const noexcept {
        return static_cast<Price>(load_be<u32>(p_ + offsetof(DirectListingWithCapitalRaise, upper_price_range_collar)));
    }

private:
    const std::byte* p_;
};

// Calls handler.on_xxx(view) for the message at p. p must point at a frame
// whose length has already been validated against message_length().
// Returns false if the type byte is not a known message type.
template <class Handler>
bool dispatch(const std::byte* p, Handler& handler) {
    switch (static_cast<char>(load_be<u8>(p))) {
        case 'S':
            if constexpr (requires { handler.on_system_event(SystemEventView{p}); }) {
                handler.on_system_event(SystemEventView{p});
            }
            return true;
        case 'R':
            if constexpr (requires { handler.on_stock_directory(StockDirectoryView{p}); }) {
                handler.on_stock_directory(StockDirectoryView{p});
            }
            return true;
        case 'H':
            if constexpr (requires { handler.on_stock_trading_action(StockTradingActionView{p}); }) {
                handler.on_stock_trading_action(StockTradingActionView{p});
            }
            return true;
        case 'Y':
            if constexpr (requires { handler.on_reg_sho_restriction(RegShoRestrictionView{p}); }) {
                handler.on_reg_sho_restriction(RegShoRestrictionView{p});
            }
            return true;
        case 'L':
            if constexpr (requires { handler.on_market_participant_position(MarketParticipantPositionView{p}); }) {
                handler.on_market_participant_position(MarketParticipantPositionView{p});
            }
            return true;
        case 'V':
            if constexpr (requires { handler.on_mwcb_decline_level(MwcbDeclineLevelView{p}); }) {
                handler.on_mwcb_decline_level(MwcbDeclineLevelView{p});
            }
            return true;
        case 'W':
            if constexpr (requires { handler.on_mwcb_status(MwcbStatusView{p}); }) {
                handler.on_mwcb_status(MwcbStatusView{p});
            }
            return true;
        case 'K':
            if constexpr (requires { handler.on_ipo_quoting_period_update(IpoQuotingPeriodUpdateView{p}); }) {
                handler.on_ipo_quoting_period_update(IpoQuotingPeriodUpdateView{p});
            }
            return true;
        case 'J':
            if constexpr (requires { handler.on_luld_auction_collar(LuldAuctionCollarView{p}); }) {
                handler.on_luld_auction_collar(LuldAuctionCollarView{p});
            }
            return true;
        case 'h':
            if constexpr (requires { handler.on_operational_halt(OperationalHaltView{p}); }) {
                handler.on_operational_halt(OperationalHaltView{p});
            }
            return true;
        case 'A':
            if constexpr (requires { handler.on_add_order(AddOrderView{p}); }) {
                handler.on_add_order(AddOrderView{p});
            }
            return true;
        case 'F':
            if constexpr (requires { handler.on_add_order_with_mpid(AddOrderWithMpidView{p}); }) {
                handler.on_add_order_with_mpid(AddOrderWithMpidView{p});
            }
            return true;
        case 'E':
            if constexpr (requires { handler.on_order_executed(OrderExecutedView{p}); }) {
                handler.on_order_executed(OrderExecutedView{p});
            }
            return true;
        case 'C':
            if constexpr (requires { handler.on_order_executed_with_price(OrderExecutedWithPriceView{p}); }) {
                handler.on_order_executed_with_price(OrderExecutedWithPriceView{p});
            }
            return true;
        case 'X':
            if constexpr (requires { handler.on_order_cancel(OrderCancelView{p}); }) {
                handler.on_order_cancel(OrderCancelView{p});
            }
            return true;
        case 'D':
            if constexpr (requires { handler.on_order_delete(OrderDeleteView{p}); }) {
                handler.on_order_delete(OrderDeleteView{p});
            }
            return true;
        case 'U':
            if constexpr (requires { handler.on_order_replace(OrderReplaceView{p}); }) {
                handler.on_order_replace(OrderReplaceView{p});
            }
            return true;
        case 'P':
            if constexpr (requires { handler.on_trade_non_cross(TradeNonCrossView{p}); }) {
                handler.on_trade_non_cross(TradeNonCrossView{p});
            }
            return true;
        case 'Q':
            if constexpr (requires { handler.on_cross_trade(CrossTradeView{p}); }) {
                handler.on_cross_trade(CrossTradeView{p});
            }
            return true;
        case 'B':
            if constexpr (requires { handler.on_broken_trade(BrokenTradeView{p}); }) {
                handler.on_broken_trade(BrokenTradeView{p});
            }
            return true;
        case 'I':
            if constexpr (requires { handler.on_noii(NoiiView{p}); }) {
                handler.on_noii(NoiiView{p});
            }
            return true;
        case 'N':
            if constexpr (requires { handler.on_retail_price_improvement(RetailPriceImprovementView{p}); }) {
                handler.on_retail_price_improvement(RetailPriceImprovementView{p});
            }
            return true;
        case 'O':
            if constexpr (requires { handler.on_direct_listing_with_capital_raise(DirectListingWithCapitalRaiseView{p}); }) {
                handler.on_direct_listing_with_capital_raise(DirectListingWithCapitalRaiseView{p});
            }
            return true;
        default:
            return false;
    }
}

}  // namespace itch::wire
