#!/usr/bin/env python3
"""Generate the wire layout and accessor headers from the extracted spec tables.

    python3 tools/gen_wire.py tools/itch50_fields.json include/itch/wire

Emits messages.hpp (layout plus static_asserts) and views.hpp (zero-copy
accessors and the dispatch switch). Both are committed, so building needs no
Python. Regenerate only when the spec changes.
"""
import json, re, sys

SPEC_SHA256 = '45e0531d1b4b3beb886e9618b2ab824a5aa9bda3a99c0dff03509306e68aacc3'
SPEC_URL = ('https://www.nasdaqtrader.com/content/technicalsupport/'
            'specifications/dataproducts/NQTVITCHspecification.pdf')

STRUCT_NAME = {
    'S': 'SystemEvent',            'R': 'StockDirectory',
    'H': 'StockTradingAction',     'Y': 'RegShoRestriction',
    'L': 'MarketParticipantPosition', 'V': 'MwcbDeclineLevel',
    'W': 'MwcbStatus',             'K': 'IpoQuotingPeriodUpdate',
    'J': 'LuldAuctionCollar',      'h': 'OperationalHalt',
    'A': 'AddOrder',               'F': 'AddOrderWithMpid',
    'E': 'OrderExecuted',          'C': 'OrderExecutedWithPrice',
    'X': 'OrderCancel',            'D': 'OrderDelete',
    'U': 'OrderReplace',           'P': 'TradeNonCross',
    'Q': 'CrossTrade',             'B': 'BrokenTrade',
    'I': 'Noii',                   'N': 'RetailPriceImprovement',
    'O': 'DirectListingWithCapitalRaise',
}

# Names the PDF's column width truncated. Completed from the same spec text;
# the offsets and lengths they attach to are still the extracted ones.
NAME_FIX = {
    # The Reg SHO table is the only one that calls the common header's second
    # field "Locate Code" instead of "Stock Locate". It is the same field at the
    # same offset; normalised so the common header is uniform across all 23
    # structs, which the parser depends on.
    ('Y', 1): 'Stock Locate',

    ('R', 20): 'Financial Status Indicator',
    ('R', 30): 'Short Sale Threshold Indicator',
    ('R', 32): 'LULD Reference Price Tier',
    ('R', 34): 'ETP Leverage Factor',
    ('K', 19): 'IPO Quotation Release Time',
    ('K', 23): 'IPO Quotation Release Qualifier',
    ('J', 31): 'Auction Collar Extension',
    ('h', 20): 'Operational Halt Action',
    ('L', 24): 'Market Maker Mode',
    ('L', 25): 'Market Participant State',
    ('A', 11): 'Order Reference Number',
    ('F', 11): 'Order Reference Number',
    ('E', 11): 'Order Reference Number',
    ('C', 11): 'Order Reference Number',
    ('P', 11): 'Order Reference Number',
    ('U', 11): 'Original Order Reference Number',
    ('U', 19): 'New Order Reference Number',
    ('I', 44): 'Current Reference Price',
    ('I', 49): 'Price Variation Indicator',
    ('F', 36): 'Attribution',
}

def snake(name):
    s = name.replace('/', ' ').replace('-', ' ')
    s = re.sub(r'[^A-Za-z0-9]+', '_', s).strip('_')
    s = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', s)
    return re.sub('_+', '_', s).lower()

def field_type(kind, length):
    if kind == 'Alpha':
        return f'Alpha<{length}>'
    if kind == 'Price':
        return {4: 'Price4', 8: 'Price8'}[length]
    return {2: 'BeU16', 4: 'BeU32', 6: 'BeU48', 8: 'BeU64'}[length]

ACCESSOR = {
    'BeU16': ('u16', 'load_be<u16>'),
    'BeU32': ('u32', 'load_be<u32>'),
    'BeU48': ('Timestamp', 'load_be48'),
    'BeU64': ('u64', 'load_be<u64>'),
    'Price4': ('Price', 'load_be<u32>'),
    'Price8': ('u64', 'load_be<u64>'),
}

def handler_name(struct):
    return 'on_' + re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', struct).lower()


def emit_views(msgs, dst):
    out = []
    w = out.append
    w('// Generated by tools/gen_wire.py. Do not edit by hand.')
    w('//')
    w('// One view per message type. A view is a bare pointer into the frame; each')
    w('// accessor decodes exactly the field asked for, at an offset taken from the')
    w('// layout struct in messages.hpp. Fields a handler never reads are never')
    w('// byteswapped, and nothing is copied.')
    w('//')
    w('// dispatch() calls handler.on_xxx(view) for the message it was given, and')
    w('// skips any handler method that does not exist, so a handler implements only')
    w('// the messages it cares about. No virtual calls, no empty overrides.')
    w('#pragma once')
    w('')
    w('#include <cstddef>')
    w('#include <string_view>')
    w('')
    w('#include "itch/core/endian.hpp"')
    w('#include "itch/core/types.hpp"')
    w('#include "itch/wire/messages.hpp"')
    w('')
    w('namespace itch::wire {')
    w('')
    w('// Alpha fields are left-justified and space padded. Returns the field with')
    w('// the padding removed.')
    w('[[nodiscard]] inline std::string_view trim_alpha(std::string_view s) noexcept {')
    w('    while (!s.empty() && s.back() == \' \') {')
    w('        s.remove_suffix(1);')
    w('    }')
    w('    return s;')
    w('}')
    w('')

    for m in msgs:
        t, name = m['type'], STRUCT_NAME[m['type']]
        view = name + 'View'
        w(f"// '{t}' -- {m['desc'].rstrip('.')}")
        w(f'class {view} {{')
        w('public:')
        w(f'    static constexpr char kType = \'{t}\';')
        w(f'    static constexpr std::size_t kSize = sizeof({name});')
        w('')
        w(f'    explicit constexpr {view}(const std::byte* p) noexcept : p_(p) {{}}')
        w('')
        w('    [[nodiscard]] const std::byte* bytes() const noexcept { return p_; }')
        w('')
        seen = {}
        for raw, off, ln, kind in m['fields']:
            fname = snake(NAME_FIX.get((t, off), raw) or f'field_{off}')
            if fname in seen:
                fname = f'{fname}_{off}'
            seen[fname] = True
            if fname == 'message_type':
                continue
            ftype = field_type(kind, ln)
            if ftype.startswith('Alpha<'):
                if ln == 1:
                    w(f'    [[nodiscard]] char {fname}() const noexcept {{')
                    w(f'        return static_cast<char>(load_be<u8>(p_ + offsetof({name}, {fname})));')
                    w('    }')
                else:
                    w(f'    [[nodiscard]] std::string_view {fname}() const noexcept {{')
                    w(f'        return std::string_view(reinterpret_cast<const char*>(p_) +')
                    w(f'                                    offsetof({name}, {fname}),')
                    w(f'                                {ln});')
                    w('    }')
            else:
                rt, fn = ACCESSOR[ftype]
                w(f'    [[nodiscard]] {rt} {fname}() const noexcept {{')
                w(f'        return static_cast<{rt}>({fn}(p_ + offsetof({name}, {fname})));')
                w('    }')
        w('')
        w('private:')
        w('    const std::byte* p_;')
        w('};')
        w('')

    w('// Calls handler.on_xxx(view) for the message at p. p must point at a frame')
    w('// whose length has already been validated against message_length().')
    w('// Returns false if the type byte is not a known message type.')
    w('template <class Handler>')
    w('bool dispatch(const std::byte* p, Handler& handler) {')
    w('    switch (static_cast<char>(load_be<u8>(p))) {')
    for m in msgs:
        name = STRUCT_NAME[m['type']]
        view = name + 'View'
        hn = handler_name(name)
        w(f"        case '{m['type']}':")
        w(f'            if constexpr (requires {{ handler.{hn}({view}{{p}}); }}) {{')
        w(f'                handler.{hn}({view}{{p}});')
        w('            }')
        w('            return true;')
    w('        default:')
    w('            return false;')
    w('    }')
    w('}')
    w('')
    w('}  // namespace itch::wire')
    open(dst, 'w').write('\n'.join(out) + '\n')
    print(f'{len(msgs)} views -> {dst}')


def main(src, dst):
    msgs = json.load(open(src))
    out = []
    w = out.append

    w('// Generated by tools/gen_wire.py. Do not edit by hand.')
    w('//')
    w('// Source: Nasdaq TotalView-ITCH 5.0 specification')
    w(f'//   {SPEC_URL}')
    w(f'//   sha256 {SPEC_SHA256}')
    w('//')
    w('// These structs pin down the wire layout and let the compiler check every')
    w('// offset. They are NOT the parse path: casting a const std::byte* to one of')
    w('// them is undefined on both alignment and aliasing grounds. Fields are read')
    w('// with load_be<T>(p + offsetof(Struct, field)) instead, so the layout here')
    w('// stays the single source of truth for every offset without any cast.')
    w('//')
    w('// Every member is a byte array, so alignment is 1 by construction and there')
    w('// is no padding anywhere. Both facts are asserted below rather than assumed.')
    w('#pragma once')
    w('')
    w('#include <cstddef>')
    w('#include <type_traits>')
    w('')
    w('#include "itch/core/types.hpp"')
    w('')
    w('namespace itch::wire {')
    w('')
    w('template <std::size_t N>')
    w('struct Bytes {')
    w('    std::byte raw[N];')
    w('};')
    w('')
    w('template <std::size_t N>')
    w('struct Alpha {')
    w('    char raw[N];')
    w('};')
    w('')
    w('using BeU16 = Bytes<2>;')
    w('using BeU32 = Bytes<4>;')
    w('using BeU48 = Bytes<6>;  // ITCH timestamps: nanoseconds since midnight')
    w('using BeU64 = Bytes<8>;')
    w('using Price4 = Bytes<4>;  // unsigned, four implied decimals')
    w('using Price8 = Bytes<8>;  // unsigned, four implied decimals')
    w('')
    w('// Longest message in the protocol. Sizing a framing buffer below this means')
    w('// a message can straddle the end of it.')
    w(f'inline constexpr std::size_t kMaxMessageLength = {max(m["size"] for m in msgs)};')
    w(f'inline constexpr std::size_t kMessageTypeCount = {len(msgs)};')
    w('')

    # enum
    w('enum class MsgType : char {')
    for m in msgs:
        w(f"    {STRUCT_NAME[m['type']]} = '{m['type']}',")
    w('};')
    w('')

    for m in msgs:
        t, name = m['type'], STRUCT_NAME[m['type']]
        w(f"// '{t}' -- {m['desc'].rstrip('.')} ({m['size']} bytes)")
        w(f'struct {name} {{')
        seen = {}
        for raw, off, ln, kind in m['fields']:
            fname = snake(NAME_FIX.get((t, off), raw) or f'field_{off}')
            if fname in seen:
                fname = f'{fname}_{off}'
            seen[fname] = True
            w(f'    {field_type(kind, ln):<10} {fname};')
        w('};')
        w(f'static_assert(sizeof({name}) == {m["size"]}, "{name} wire size");')
        w(f'static_assert(alignof({name}) == 1, "{name} must have no alignment padding");')
        w(f'static_assert(std::is_standard_layout_v<{name}>, "{name} must be standard layout for offsetof");')
        seen = {}
        for raw, off, ln, kind in m['fields']:
            fname = snake(NAME_FIX.get((t, off), raw) or f'field_{off}')
            if fname in seen:
                fname = f'{fname}_{off}'
            seen[fname] = True
            w(f'static_assert(offsetof({name}, {fname}) == {off}, "{name}::{fname} offset");')
            w(f'static_assert(sizeof({name}::{fname}) == {ln}, "{name}::{fname} length");')
        w('')

    # length table
    w('// Declared body length for a message type, or 0 if the type is unknown.')
    w('// The framing layer cross-checks this against the length prefix on the wire,')
    w('// which turns the real feed into a test of every size above.')
    w('[[nodiscard]] constexpr std::size_t message_length(char type) noexcept {')
    w('    switch (type) {')
    for m in msgs:
        w(f"        case '{m['type']}': return sizeof({STRUCT_NAME[m['type']]});")
    w('        default: return 0;')
    w('    }')
    w('}')
    w('')
    w('// Short name for a message type, for reporting. "unknown" if not a type.')
    w('[[nodiscard]] constexpr const char* type_name(char type) noexcept {')
    w('    switch (type) {')
    for m in msgs:
        w(f"""        case '{m['type']}': return "{STRUCT_NAME[m['type']]}";""")
    w('        default: return "unknown";')
    w('    }')
    w('}')
    w('')
    w('[[nodiscard]] constexpr bool is_known_type(char type) noexcept {')
    w('    return message_length(type) != 0;')
    w('}')
    w('')
    w('}  // namespace itch::wire')

    import os
    open(os.path.join(dst, 'messages.hpp'), 'w').write('\n'.join(out) + '\n')
    total = sum(len(m['fields']) for m in msgs)
    print(f"{len(msgs)} messages, {total} fields, "
          f"{2 * total + 3 * len(msgs)} static_asserts -> {dst}/messages.hpp")
    emit_views(msgs, os.path.join(dst, 'views.hpp'))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
